import { BASE_URL } from '@/config/index';

const title = 'coffmanjrp.io';
const description = 'Generated by create next app';

const SEO = {
  titleTemplate: `%s | ${title}`,
  defaultTitle: title,
  description,
  canonical: BASE_URL,
  openGraph: {
    type: 'website',
    locale: 'en_IE',
    url: BASE_URL,
    title,
    description,
    images: {
      url: `${BASE_URL}/og.png`,
      alt: title,
      width: 1280,
      height: 720,
    },
  },
  additionalLinkTags: [
    {
      rel: 'icon',
      href: `/favicon.ico`,
    },
  ],
};

export default SEO;
